name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Get release version from tag
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Create GitHub Release and Upload Files
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          name: ${{ github.event.repository.name }}-${{ env.VERSION }}
          generate_release_notes: true
